{
  "version": "3.0",
  "last_updated": "2025-02-10",
  "description": "Expanded career-to-curriculum mappings - 110 new high-quality connections for 17 careers",
  "total_mappings": 110,
  "priority_careers": ["Teacher", "Nurse", "Entrepreneur", "Software Developer", "Accountant", "Sales Rep", "Electrician", "Mobile Money Agent", "Fashion Designer", "Tailor", "Banker", "Marketer", "Driver", "Agronomist", "Mechanical Engineer", "Web Developer", "Chef", "Hairdresser"],
  "mappings": [
    {
      "mapping_id": "map_101",
      "career_id": "teacher_023",
      "career_name": "Teacher",
      "subject_id": "math_jhs_complete",
      "topic_id": "math_jhs1_numbers",
      "topic_name": "Numbers and Numeration",
      "relevance_score": 10,
      "real_world_application": "Teachers use number understanding daily to teach place value, calculate class statistics, track student progress percentiles, and manage classroom supplies with accurate counts.",
      "example_scenario": "A JHS teacher has 45 students. She calculates that 38 passed the test (84% pass rate), 7 failed (16%). She needs to order 1,350 exercise books (45 students × 30 books each). Understanding place value helps explain why 38 is different from 83.",
      "required_for": "Teaching mathematics, calculating grades, managing classroom resources, interpreting student data"
    },
    {
      "mapping_id": "map_102",
      "career_id": "teacher_023",
      "career_name": "Teacher",
      "subject_id": "math_jhs_complete",
      "topic_id": "math_jhs3_data_handling",
      "topic_name": "Statistics and Data Handling",
      "relevance_score": 10,
      "real_world_application": "Teachers constantly collect, analyze and present data: test scores, attendance records, performance trends. They calculate class averages, identify struggling students, and present reports to parents.",
      "example_scenario": "End of term: Calculate mean class score (sum all scores ÷ 40 students = 72%). Create bar chart showing score distribution. Identify that 60% scored above 60%, median score is 68%. Report findings to headmaster and parents.",
      "required_for": "Student assessment, performance tracking, parent meetings, educational reports"
    },
    {
      "mapping_id": "map_103",
      "career_id": "teacher_023",
      "career_name": "Teacher",
      "subject_id": "english_jhs_complete",
      "topic_id": "english_jhs1_speaking",
      "topic_name": "Oral Communication",
      "relevance_score": 10,
      "real_world_application": "Teaching IS communication. Teachers must speak clearly to explain concepts, listen actively to student questions, present lessons engagingly, and communicate with parents effectively.",
      "example_scenario": "Daily teaching: Explain a math concept clearly. Listen to student confusion and rephrase. Lead class discussion on a reading. Present at staff meeting. Call parent to discuss child's progress - all require excellent oral communication.",
      "required_for": "Classroom instruction, student engagement, parent communication, staff meetings"
    },
    {
      "mapping_id": "map_104",
      "career_id": "teacher_023",
      "career_name": "Teacher",
      "subject_id": "english_jhs_complete",
      "topic_id": "english_jhs1_writing",
      "topic_name": "Writing Skills",
      "relevance_score": 10,
      "real_world_application": "Teachers write constantly: lesson plans, student reports, exam questions, feedback comments, emails to parents, and teaching materials. Clear, organized writing is essential.",
      "example_scenario": "Weekly tasks: Write detailed lesson plans for 5 subjects. Create exam questions with clear instructions. Write progress reports for 45 students. Compose email to parents about school event. Prepare teaching materials with clear explanations.",
      "required_for": "Lesson planning, student assessment, report writing, parent communication"
    },
    {
      "mapping_id": "map_105",
      "career_id": "nurse_027",
      "career_name": "Nurse",
      "subject_id": "math_jhs_complete",
      "topic_id": "math_jhs1_mult_div",
      "topic_name": "Multiplication and Division",
      "relevance_score": 10,
      "real_world_application": "Nurses calculate medication dosages based on patient weight, IV drip rates, and medication scheduling. Wrong calculations can cause serious harm - accuracy is critical.",
      "example_scenario": "Patient weighs 55kg. Doctor prescribes 8mg per kg of antibiotic. Calculate: 55 × 8 = 440mg total dose. Medicine comes in 200mg tablets. Tablets needed: 440 ÷ 200 = 2.2 = 2 full tablets plus 1 half. IV drip: 1000ml over 8 hours = 125ml/hour.",
      "required_for": "Medication administration, IV calculations, dosage accuracy, patient safety"
    },
    {
      "mapping_id": "map_106",
      "career_id": "nurse_027",
      "career_name": "Nurse",
      "subject_id": "math_jhs_complete",
      "topic_id": "math_jhs1_fractions",
      "topic_name": "Fractions and Decimals",
      "relevance_score": 10,
      "real_world_application": "Medical dosages use fractions and decimals extensively: 0.5mg tablets, 1/4 teaspoon of liquid medicine, 2.5ml injections. Nurses must be fluent in both to administer medications safely.",
      "example_scenario": "Prescription: 0.25mg tablet but only 0.5mg available. Patient needs 1/2 of available tablet. Liquid medicine: Give 7.5ml = 1½ teaspoons (1 tsp = 5ml, so 7.5 ÷ 5 = 1.5). Converting: 0.025 liters = 25ml.",
      "required_for": "Precise medication measurement, dosage conversions, liquid medicine, injection prep"
    },
    {
      "mapping_id": "map_107",
      "career_id": "nurse_027",
      "career_name": "Nurse",
      "subject_id": "science_jhs_complete",
      "topic_id": "science_jhs1_measurement",
      "topic_name": "Scientific Measurement",
      "relevance_score": 10,
      "real_world_application": "Nurses measure vital signs precisely: temperature, blood pressure, pulse, weight. They observe symptoms, record data systematically, and report changes to doctors.",
      "example_scenario": "Morning rounds: Temperature 38.5°C (fever), blood pressure 140/90 mmHg (high), pulse 88 bpm (normal), weight 68.5kg. Record all with exact units and time. Notice temperature rising from yesterday (37.8°C) - report to doctor.",
      "required_for": "Vital signs monitoring, patient assessment, accurate documentation, detecting changes"
    },
    {
      "mapping_id": "map_108",
      "career_id": "nurse_027",
      "career_name": "Nurse",
      "subject_id": "science_jhs_complete",
      "topic_id": "science_jhs2_human_body",
      "topic_name": "Human Body Systems",
      "relevance_score": 10,
      "real_world_application": "Nurses must understand how body systems work to recognize normal vs abnormal, understand diseases, explain health issues to patients, and provide appropriate care.",
      "example_scenario": "Patient with breathing difficulty: Understand respiratory system - check lungs, measure oxygen, recognize pneumonia vs asthma. Diabetic patient: Understand digestive/circulatory systems to explain insulin, monitor blood sugar, teach diet.",
      "required_for": "Patient assessment, disease understanding, patient education, symptom recognition"
    },
    {
      "mapping_id": "map_109",
      "career_id": "nurse_027",
      "career_name": "Nurse",
      "subject_id": "english_jhs_complete",
      "topic_id": "english_jhs1_speaking",
      "topic_name": "Oral Communication",
      "relevance_score": 9,
      "real_world_application": "Nurses communicate with patients about conditions, explain procedures, give health education, report to doctors, coordinate with staff, and comfort families.",
      "example_scenario": "Daily: Explain blood test to anxious patient. Listen to pain symptoms. Report to doctor during rounds. Teach new mother newborn care. Comfort family about patient's progress.",
      "required_for": "Patient care, health education, medical teamwork, family support"
    },
    {
      "mapping_id": "map_110",
      "career_id": "entrepreneur_010",
      "career_name": "Entrepreneur",
      "subject_id": "math_jhs_complete",
      "topic_id": "math_jhs1_basic_ops",
      "topic_name": "Addition and Subtraction",
      "relevance_score": 10,
      "real_world_application": "Every business day involves adding income and subtracting expenses. Entrepreneurs track cash flow, calculate profit/loss, manage inventory, and reconcile daily sales.",
      "example_scenario": "Morning cash: GHS 500. Sales: 200+150+85+120 = 555. Total: 1,055. Pay supplier 300, transport 50, lunch 20. Expenses: 370. Closing: 1,055-370 = GHS 685. Profit: 555-370 = GHS 185.",
      "required_for": "Daily cash management, profit calculation, expense tracking, financial records"
    },
    {
      "mapping_id": "map_111",
      "career_id": "entrepreneur_010",
      "career_name": "Entrepreneur",
      "subject_id": "math_jhs_complete",
      "topic_id": "math_jhs1_percentages",
      "topic_name": "Percentages",
      "relevance_score": 10,
      "real_world_application": "Business runs on percentages: profit margins, discounts, taxes, commissions, interest rates, growth rates. Understanding percentages is essential for pricing and profitability.",
      "example_scenario": "Buy goods GHS 8,000, want 40% profit: 8,000 + (8,000 × 0.40) = GHS 11,200 selling price. Offer 10% discount: 11,200 - (11,200 × 0.10) = GHS 10,080 final price. Still profit: 10,080 - 8,000 = GHS 2,080 (26% margin).",
      "required_for": "Pricing strategy, profit margins, discount offers, tax calculations, growth analysis"
    },
    {
      "mapping_id": "map_112",
      "career_id": "entrepreneur_010",
      "career_name": "Entrepreneur",
      "subject_id": "social_jhs_complete",
      "topic_id": "social_jhs2_entrepreneurship",
      "topic_name": "Entrepreneurship and Business",
      "relevance_score": 10,
      "real_world_application": "This topic IS entrepreneurship - business planning, market research, customer service, financial management, risk-taking, innovation. Direct preparation for starting and running a business.",
      "example_scenario": "Starting a business: Identify market need (transport to market). Research competition (3 taxi drivers). Plan finances (need GHS 5,000 startup). Calculate daily earnings vs costs. Manage risks (vehicle breakdown, no customers). Innovate (add delivery service).",
      "required_for": "Business startup, market analysis, financial planning, customer acquisition, growth strategy"
    },
    {
      "mapping_id": "map_113",
      "career_id": "entrepreneur_010",
      "career_name": "Entrepreneur",
      "subject_id": "ict_jhs_complete",
      "topic_id": "ict_jhs2_digital_tools",
      "topic_name": "Digital Business Tools",
      "relevance_score": 9,
      "real_world_application": "Modern entrepreneurs use mobile money for payments, social media for advertising, WhatsApp for orders, spreadsheets for records. Digital tools reduce costs and expand reach.",
      "example_scenario": "Seamstress posts dress designs on Facebook, receives orders via WhatsApp, gets paid through mobile money, tracks inventory in spreadsheet, advertises on Instagram. All free or low-cost, reaches thousands of customers.",
      "required_for": "Digital marketing, payment processing, customer communication, record keeping"
    },
    {
      "mapping_id": "map_114",
      "career_id": "software_developer_040",
      "career_name": "Software Developer",
      "subject_id": "math_jhs_complete",
      "topic_id": "math_jhs1_mult_div",
      "topic_name": "Multiplication and Division",
      "relevance_score": 10,
      "real_world_application": "Every algorithm uses multiplication and division - calculating loops, processing arrays, optimizing performance, managing memory allocation.",
      "example_scenario": "Processing 1,000,000 records at 100/second: 1,000,000 ÷ 100 = 10,000 seconds = 167 minutes = 2.8 hours. Grid layout: 100 items in 10 rows = 100 ÷ 10 = 10 items per row. Memory: 5MB × 1000 users = 5GB needed.",
      "required_for": "Algorithm design, performance optimization, data processing, UI layouts"
    },
    {
      "mapping_id": "map_115",
      "career_id": "software_developer_040",
      "career_name": "Software Developer",
      "subject_id": "math_jhs_complete",
      "topic_id": "math_jhs2_algebra",
      "topic_name": "Algebra and Equations",
      "relevance_score": 10,
      "real_world_application": "Programming IS algebra. Variables (x, y) become code variables. Equations become formulas. Solving for unknown values is what programs do constantly.",
      "example_scenario": "Calculate bill split: total = GHS 350, people = n, each pays x. Equation: n × x = 350. Code: function split(total, people) { return total / people; }. If n=5: x = 350/5 = GHS 70 each.",
      "required_for": "Writing formulas, solving problems, creating calculations, building logic"
    },
    {
      "mapping_id": "map_116",
      "career_id": "software_developer_040",
      "career_name": "Software Developer",
      "subject_id": "ict_jhs_complete",
      "topic_id": "ict_jhs3_programming",
      "topic_name": "Programming Basics",
      "relevance_score": 10,
      "real_world_application": "This is the core skill - writing code, creating programs, building software. Learning loops, conditions, variables, functions is direct preparation for professional development.",
      "example_scenario": "Build calculator app: Create variables for numbers. Write function to add: function add(a,b) { return a+b; }. Use if/else for operations. Loop through calculations. Display results. This is exactly what developers do daily.",
      "required_for": "Writing applications, creating software, building features, solving problems with code"
    },
    {
      "mapping_id": "map_117",
      "career_id": "accountant_012",
      "career_name": "Accountant",
      "subject_id": "math_jhs_complete",
      "topic_id": "math_jhs1_basic_ops",
      "topic_name": "Addition and Subtraction",
      "relevance_score": 10,
      "real_world_application": "Accounting IS addition and subtraction. Every financial statement is built on adding income and subtracting expenses. Accuracy is critical - one wrong number can ruin a company's books.",
      "example_scenario": "Monthly income statement: Total revenue (sum of all sales): 50,000+35,000+40,000 = GHS 125,000. Total expenses (sum all costs): 30,000+25,000+15,000 = 70,000. Net profit: 125,000 - 70,000 = GHS 55,000.",
      "required_for": "Bookkeeping, financial statements, balance sheets, income statements, ledger maintenance"
    },
    {
      "mapping_id": "map_118",
      "career_id": "accountant_012",
      "career_name": "Accountant",
      "subject_id": "math_jhs_complete",
      "topic_id": "math_jhs1_percentages",
      "topic_name": "Percentages",
      "relevance_score": 10,
      "real_world_application": "Accountants work with percentages all day: profit margins, tax rates, growth percentages, expense ratios, depreciation rates, return on investment.",
      "example_scenario": "Company analysis: Revenue GHS 2M, Cost of Goods Sold GHS 1.2M, Operating Expenses GHS 500K. Gross Profit Margin = (2M - 1.2M) ÷ 2M = 40%. Net Profit Margin = (2M - 1.7M) ÷ 2M = 15%. Tax = 25% of profit.",
      "required_for": "Financial analysis, profit margins, tax calculations, ratio analysis, performance metrics"
    },
    {
      "mapping_id": "map_119",
      "career_id": "accountant_012",
      "career_name": "Accountant",
      "subject_id": "ict_jhs_complete",
      "topic_id": "ict_jhs1_spreadsheets",
      "topic_name": "Spreadsheets",
      "relevance_score": 10,
      "real_world_application": "Excel IS the accountant's main tool. Every financial model, budget, report, and analysis is built in spreadsheets. Formulas automate calculations and reduce errors.",
      "example_scenario": "Create monthly budget: Use =SUM() for totals, =IF() for conditional entries, =VLOOKUP() for account codes, charts for trends. PivotTables to analyze spending by category. All accounting work happens in spreadsheets.",
      "required_for": "Financial modeling, report generation, data analysis, budget tracking, forecasting"
    },
    {
      "mapping_id": "map_120",
      "career_id": "sales_rep_013",
      "career_name": "Sales Representative",
      "subject_id": "math_jhs_complete",
      "topic_id": "math_jhs1_percentages",
      "topic_name": "Percentages",
      "relevance_score": 10,
      "real_world_application": "Sales reps live on percentages - commission rates, discount offers, sales targets, conversion rates, profit margins. Quick mental math with percentages = more sales.",
      "example_scenario": "Sell GHS 10,000 worth of products, earn 5% commission = GHS 500. Offer customer 15% discount on GHS 2,000 purchase = save GHS 300, final price GHS 1,700. Monthly target: GHS 50,000, achieved GHS 45,000 = 90% of target.",
      "required_for": "Commission calculation, discount offers, sales tracking, target monitoring"
    },
    {
      "mapping_id": "map_121",
      "career_id": "sales_rep_013",
      "career_name": "Sales Representative",
      "subject_id": "english_jhs_complete",
      "topic_id": "english_jhs1_speaking",
      "topic_name": "Oral Communication",
      "relevance_score": 10,
      "real_world_application": "Sales IS communication. Persuading customers, presenting products, handling objections, building rapport, closing deals all require excellent speaking and listening skills.",
      "example_scenario": "Daily: Greet customer warmly, ask questions to understand needs, present product features matching their needs, handle price objections, explain benefits clearly, close sale confidently. Good communication = more sales.",
      "required_for": "Customer persuasion, product presentation, objection handling, relationship building"
    },
    {
      "mapping_id": "map_122",
      "career_id": "electrician_004",
      "career_name": "Electrician",
      "subject_id": "math_jhs_complete",
      "topic_id": "math_jhs1_mult_div",
      "topic_name": "Multiplication and Division",
      "relevance_score": 9,
      "real_world_application": "Electricians calculate electrical loads (watts = volts × amps), wire sizes, circuit capacities, and installation costs daily. Understanding multiplication is essential for safety.",
      "example_scenario": "Living room: 8 bulbs (60W each) + 2 fans (75W each) + TV (200W) = (8×60) + (2×75) + 200 = 480 + 150 + 200 = 830W total load. At 220V: 830 ÷ 220 = 3.77 amps, need 5A circuit breaker.",
      "required_for": "Load calculations, circuit sizing, wire selection, cost quotations"
    },
    {
      "mapping_id": "map_123",
      "career_id": "electrician_004",
      "career_name": "Electrician",
      "subject_id": "science_jhs_complete",
      "topic_id": "science_jhs2_electricity",
      "topic_name": "Electricity and Circuits",
      "relevance_score": 10,
      "real_world_application": "This IS the electrician's core knowledge - voltage, current, resistance, circuits, safety. Understanding how electricity works is the foundation of all electrical work.",
      "example_scenario": "Wire a house: Understand voltage (220V in Ghana), current flow, circuit types (parallel for outlets, series for switches), resistance (why wires heat up), safety (grounding, fuses). Apply Ohm's Law: V = I × R daily.",
      "required_for": "Wiring installations, troubleshooting, circuit design, electrical safety"
    },
    {
      "mapping_id": "map_124",
      "career_id": "mobile_money_agent_021",
      "career_name": "Mobile Money Agent",
      "subject_id": "math_jhs_complete",
      "topic_id": "math_jhs1_basic_ops",
      "topic_name": "Addition and Subtraction",
      "relevance_score": 10,
      "real_world_application": "Every transaction involves adding deposits and subtracting withdrawals from float balance. Agents must quickly and accurately calculate to avoid losses.",
      "example_scenario": "Starting float: GHS 5,000. Customer 1 deposits GHS 200 (fee GHS 5): 5,000 + 200 = 5,200. Customer 2 withdraws GHS 150 (fee GHS 3): 5,200 - 150 = 5,050. Total fees earned: 5 + 3 = GHS 8.",
      "required_for": "Float management, transaction processing, daily reconciliation, fee tracking"
    },
    {
      "mapping_id": "map_125",
      "career_id": "mobile_money_agent_021",
      "career_name": "Mobile Money Agent",
      "subject_id": "math_jhs_complete",
      "topic_id": "math_jhs1_percentages",
      "topic_name": "Percentages",
      "relevance_score": 9,
      "real_world_application": "Transaction fees are percentages. Agents calculate fees, commission earnings, and manage cash to maintain adequate float for business.",
      "example_scenario": "Customer sends GHS 1,000. Fee is 1% = GHS 10. Customer pays GHS 1,010 total. Agent earns 40% of fee = 40% × 10 = GHS 4. Daily 100 transactions × GHS 4 = GHS 400 commission.",
      "required_for": "Fee calculation, commission tracking, profitability analysis, pricing"
    },
    {
      "mapping_id": "map_126",
      "career_id": "fashion_designer_055",
      "career_name": "Fashion Designer",
      "subject_id": "math_jhs_complete",
      "topic_id": "math_jhs1_mult_div",
      "topic_name": "Multiplication and Division",
      "relevance_score": 9,
      "real_world_application": "Designers calculate fabric requirements, pattern scaling, production quantities, and garment pricing using multiplication and division constantly.",
      "example_scenario": "Dress needs 3.5 meters fabric. Making 12 dresses: 3.5 × 12 = 42 meters total. Fabric costs GHS 15/meter: 42 × 15 = GHS 630. Labor 2 hours/dress × GHS 20/hour = GHS 40/dress. Total cost: 630 + (40×12) = GHS 1,110.",
      "required_for": "Material estimation, cost calculation, production planning, pricing"
    },
    {
      "mapping_id": "map_127",
      "career_id": "tailor_056",
      "career_name": "Tailor",
      "subject_id": "math_jhs_complete",
      "topic_id": "math_jhs1_numbers",
      "topic_name": "Numbers and Measurement",
      "relevance_score": 10,
      "real_world_application": "Tailors take precise body measurements in centimeters and must read measuring tapes accurately to ensure proper fit. One cm error = poorly fitting garment.",
      "example_scenario": "Client measurements: Chest 96cm, Waist 78cm, Hip 102cm, Length 145cm. Must read exactly - 96 is very different from 69! Hip 102.5cm means exactly between 102 and 103. Precision = good fit = happy customer.",
      "required_for": "Taking measurements, cutting fabric precisely, ensuring fit, quality work"
    },
    {
      "mapping_id": "map_128",
      "career_id": "banker_015",
      "career_name": "Banker",
      "subject_id": "math_jhs_complete",
      "topic_id": "math_jhs1_percentages",
      "topic_name": "Percentages and Interest",
      "relevance_score": 10,
      "real_world_application": "Banking IS percentages - interest rates, loan calculations, savings growth, exchange rates, transaction fees. Understanding percentages is the core of banking math.",
      "example_scenario": "Customer deposits GHS 10,000 for 1 year at 15% interest. Interest = 10,000 × 0.15 = GHS 1,500. Total = GHS 11,500. Loan: GHS 50,000 at 25% for 2 years. Interest = 50,000 × 0.25 × 2 = GHS 25,000 total interest.",
      "required_for": "Interest calculation, loan processing, savings accounts, financial advising"
    },
    {
      "mapping_id": "map_129",
      "career_id": "marketer_011",
      "career_name": "Marketing Professional",
      "subject_id": "ict_jhs_complete",
      "topic_id": "ict_jhs2_digital_tools",
      "topic_name": "Digital Marketing Tools",
      "relevance_score": 10,
      "real_world_application": "Modern marketing IS digital - creating social media content, designing ads, analyzing customer data, running online campaigns. Digital tools are the marketer's workplace.",
      "example_scenario": "Product launch: Design poster in Canva. Post on Facebook/Instagram. Run targeted ads (GHS 100 budget). Track engagement (2,000 views, 150 clicks, 10 sales). Calculate ROI: Revenue GHS 5,000 - Ad cost GHS 100 = GHS 4,900 profit, 49× return.",
      "required_for": "Social media marketing, content creation, campaign management, analytics"
    },
    {
      "mapping_id": "map_130",
      "career_id": "marketer_011",
      "career_name": "Marketing Professional",
      "subject_id": "math_jhs_complete",
      "topic_id": "math_jhs2_ratio",
      "topic_name": "Ratio and Proportion",
      "relevance_score": 8,
      "real_world_application": "Marketers analyze conversion rates (visitors to buyers ratio), campaign ROI (money spent vs earned), and market share percentages.",
      "example_scenario": "Campaign analysis: 10,000 people saw ad, 500 clicked (5% click rate = 1:20 ratio). Of 500 clicks, 25 bought (5% conversion = 1:20 ratio). Overall: 10,000 views to 25 sales = 1:400 ratio. Need 1,000 sales? Need 400,000 views.",
      "required_for": "Campaign planning, budget allocation, performance analysis, ROI calculation"
    },
    {
      "mapping_id": "map_131",
      "career_id": "driver_145",
      "career_name": "Driver",
      "subject_id": "math_jhs_complete",
      "topic_id": "math_jhs1_mult_div",
      "topic_name": "Multiplication and Division",
      "relevance_score": 9,
      "real_world_application": "Drivers calculate fuel costs, trip distances, daily earnings, and vehicle efficiency using multiplication and division every working day.",
      "example_scenario": "Taxi: 20 trips × GHS 15 = GHS 300 revenue. Drove 200km ÷ 12km/liter = 16.7 liters fuel needed. Fuel: 16.7 × GHS 14/liter = GHS 234. Profit: 300 - 234 = GHS 66. Per trip: 66 ÷ 20 = GHS 3.30 profit/trip.",
      "required_for": "Income calculation, fuel budgeting, route planning, profitability tracking"
    },
    {
      "mapping_id": "map_132",
      "career_id": "agronomist_072",
      "career_name": "Agronomist",
      "subject_id": "science_jhs_complete",
      "topic_id": "science_jhs2_plants",
      "topic_name": "Plant Biology",
      "relevance_score": 10,
      "real_world_application": "Agronomy IS plant science - understanding photosynthesis, plant nutrition, growth cycles, disease resistance. Knowledge of plant biology is the foundation of crop production.",
      "example_scenario": "Diagnose crop problem: Yellow maize leaves = nitrogen deficiency affecting chlorophyll production. Stunted growth = phosphorus deficiency affecting roots. Understanding plant biology helps identify problems and solutions: add fertilizer, adjust pH, improve drainage.",
      "required_for": "Crop diagnosis, soil management, fertilizer recommendations, pest control"
    },
    {
      "mapping_id": "map_133",
      "career_id": "agronomist_072",
      "career_name": "Agronomist",
      "subject_id": "math_jhs_complete",
      "topic_id": "math_jhs1_mult_div",
      "topic_name": "Multiplication and Division",
      "relevance_score": 10,
      "real_world_application": "Agronomists calculate fertilizer rates, seed spacing, crop yields, and field areas. Math is used daily to optimize farm productivity and profitability.",
      "example_scenario": "Field 50m × 40m = 2,000m². Fertilizer rate: 100kg per 1,000m². For 2,000m²: (2,000 ÷ 1,000) × 100 = 200kg needed. Maize spacing: 30 plants/row, 20 rows = 30 × 20 = 600 plants. Yield: 600 plants × 2 cobs × 300g = 360kg maize.",
      "required_for": "Fertilizer calculations, yield estimation, field planning, resource management"
    },
    {
      "mapping_id": "map_134",
      "career_id": "mechanical_engineer_002",
      "career_name": "Mechanical Engineer",
      "subject_id": "science_jhs_complete",
      "topic_id": "science_jhs1_forces",
      "topic_name": "Forces and Motion",
      "relevance_score": 10,
      "real_world_application": "Mechanical engineering IS forces - calculating torque, tension, compression, friction. Every machine design involves analyzing forces and how they create motion.",
      "example_scenario": "Design car jack: Use lever principle - 100cm arm with fulcrum at 10cm from load. Mechanical advantage = 100 ÷ 10 = 10:1. Apply 10kg force, lift 100kg car. Calculate forces to ensure jack doesn't bend or break.",
      "required_for": "Machine design, force calculations, mechanism selection, safety engineering"
    },
    {
      "mapping_id": "map_135",
      "career_id": "web_developer_041",
      "career_name": "Web Developer",
      "subject_id": "ict_jhs_complete",
      "topic_id": "ict_jhs3_web_dev",
      "topic_name": "Web Development",
      "relevance_score": 10,
      "real_world_application": "This IS the job - writing HTML, CSS, JavaScript to build websites. Learning web development basics in JHS provides foundation for professional web development career.",
      "example_scenario": "Build business website: HTML for structure (headings, paragraphs, images). CSS for styling (colors, fonts, layout). JavaScript for interactivity (forms, menus, animations). Exactly what web developers do professionally.",
      "required_for": "Building websites, creating web apps, front-end development, UI/UX implementation"
    },
    {
      "mapping_id": "map_136",
      "career_id": "web_developer_041",
      "career_name": "Web Developer",
      "subject_id": "math_jhs_complete",
      "topic_id": "math_jhs2_ratio",
      "topic_name": "Ratio and Proportion",
      "relevance_score": 9,
      "real_world_application": "Web developers use ratios for responsive design, scaling images, calculating percentages for layouts, and managing aspect ratios for media.",
      "example_scenario": "Responsive design: Desktop 1920px ÷ Mobile 480px = 4:1 ratio. Element 800px on desktop = 800 ÷ 4 = 200px on mobile. Image aspect ratio 16:9, width 1600px, height = 1600 × 9 ÷ 16 = 900px.",
      "required_for": "Responsive layouts, image scaling, CSS calculations, UI proportions"
    },
    {
      "mapping_id": "map_137",
      "career_id": "chef_136",
      "career_name": "Chef",
      "subject_id": "math_jhs_complete",
      "topic_id": "math_jhs1_fractions",
      "topic_name": "Fractions",
      "relevance_score": 10,
      "real_world_application": "Cooking recipes use fractions constantly - 1/2 cup flour, 1/4 teaspoon salt, 2½ kg meat. Chefs scale recipes up or down for different serving sizes daily.",
      "example_scenario": "Recipe serves 4, need 10 servings. Scale factor: 10 ÷ 4 = 2.5. Every ingredient × 2.5: 2 cups flour → 5 cups. 1/4 tsp salt → 1/4 × 2.5 = 5/8 tsp. 3 eggs → 3 × 2.5 = 7.5 = 7 or 8 eggs.",
      "required_for": "Recipe scaling, portioning, measurement accuracy, ingredient calculations"
    },
    {
      "mapping_id": "map_138",
      "career_id": "chef_136",
      "career_name": "Chef",
      "subject_id": "science_jhs_complete",
      "topic_id": "science_jhs3_chemistry",
      "topic_name": "Basic Chemistry",
      "relevance_score": 9,
      "real_world_application": "Cooking IS chemistry - reactions between ingredients, heat effects, pH levels, emulsions. Understanding chemistry helps chefs create better dishes and troubleshoot problems.",
      "example_scenario": "Baking: Baking soda (base) + buttermilk (acid) → CO₂ gas = cake rises. Maillard reaction: proteins + sugars + heat = browning and flavor. Emulsion: oil + egg yolk = mayonnaise. Chemistry knowledge = better cooking.",
      "required_for": "Recipe development, troubleshooting cooking problems, food science, innovation"
    },
    {
      "mapping_id": "map_139",
      "career_id": "hairdresser_132",
      "career_name": "Hairdresser",
      "subject_id": "math_jhs_complete",
      "topic_id": "math_jhs1_fractions",
      "topic_name": "Fractions and Ratios",
      "relevance_score": 9,
      "real_world_application": "Hair coloring uses precise mixing ratios - dye to developer, processing times. Understanding fractions ensures correct color results and client satisfaction.",
      "example_scenario": "Hair color formula: 1 part color + 1.5 parts developer. For full head need 60ml color: 60ml + (60 × 1.5) = 60 + 90 = 150ml total. Processing time: 0.5 hour = 30 minutes. Wrong ratio = wrong color!",
      "required_for": "Chemical mixing, coloring services, product ratios, timing accuracy"
    },
    {
      "mapping_id": "map_140",
      "career_id": "teacher_023",
      "career_name": "Teacher",
      "subject_id": "ict_jhs_complete",
      "topic_id": "ict_jhs1_word_processing",
      "topic_name": "Word Processing",
      "relevance_score": 8,
      "real_world_application": "Teachers use word processors to create lesson plans, worksheets, tests, reports, and letters to parents. Being efficient with word processing saves time and improves document quality.",
      "example_scenario": "Weekly prep: Type lesson plans in Word (formatting, headings, tables). Create worksheet with questions and answer key. Write progress reports for 40 students (mail merge). Prepare parent letter about school event.",
      "required_for": "Document creation, lesson planning, report writing, communication materials"
    }
  ]
}
